-- MySQL Script generated by MySQL Workbench
-- lun. 30 mai 2022 12:16:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema music-analysis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music-analysis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music-analysis` ;
USE `music-analysis` ;

-- -----------------------------------------------------
-- Table `music-analysis`.`Music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-analysis`.`Music` (
  `idMusic` INT NOT NULL,
  `Url` VARCHAR(255) NULL,
  `Title` VARCHAR(255) NULL,
  `Duration` TIME NULL,
  `TempoMoy` VARCHAR(45) NULL,
  `TempoMax` VARCHAR(45) NULL,
  `TempoMin` VARCHAR(45) NULL,
  `HarmonicsMin` VARCHAR(45) NULL,
  `HarmonicsMoy` VARCHAR(45) NULL,
  `HarmonicsMax` VARCHAR(45) NULL,
  `FrequencyMin` VARCHAR(45) NULL,
  `FrequencyMoy` VARCHAR(45) NULL,
  `FrequencyMax` VARCHAR(45) NULL,
  `PowerMin` VARCHAR(45) NULL,
  `PowerMoy` VARCHAR(45) NULL,
  `PowerMax` VARCHAR(45) NULL,
  `RatioF/T` VARCHAR(45) NULL,
  PRIMARY KEY (`idMusic`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
